pygments:         true
permalink:        pretty
markdown:         rdiscount
rdiscount:
  extensions:     [smart]

# ---------
# Kickstarter specific settings
#
# Basics
#
# 0. Page title and theme
title:            Hootlife
theme:            basic
#
# 1. Your website ( could be same as this page - see below )
website:          http://www.hootlife.com
#
# 2. URL of this page
url:              Please share Hootlife with your friends on Facebook! http://hootlife.github.io
#
# 3. About your kickstarter project
project: 
  #
  # Name of the project
  name:           Want To Avoid a DUI? There's An App For That...Soon!
  #
  # URL of the project. Use short urls to ensure you track the visits (Optional)
  url:            igg.me/at/hootlifeapp         
  #
  # URL of a cover photo of your project
  cover_image:    https://lh5.googleusercontent.com/-5zv_J1D_eGY/U1sS5-HK4MI/AAAAAAAAADA/fESoa3pIrO8/s630-fcrop64=1,1b420000e84add28/hootlife_owl.png
  #
  # Use a one-liner to describe your project
  description:    Our goal is to cultivate social awareness in nightlife with each interaction we create. App coming soon!
#
# 4. Your Twitter handle
twitter_handle:   HootLife
#
# 5. Your Google analytics ID (Optional)
google_analytics: 
#
# 6. Welcome text, add <br /> to break lines
welcome_text:     |
  This is the Hootlife team greeting you from Wilmington, NC. <br />
  First of all, thank you for your interest. <br />
  We're here to tell you that our project is now live on Indiegogo,
  and now we have to count on your support to not only back the project, but also share the love. ♥
